config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'products#index'


  get "/about" => "pages#about"
  get "/grid" => "pages#grid"

  resources :products
  resources :upvotes, only: [ :create, :destroy ]

  #read actions routes
  get "/products/:id" => "products#show"
  get "/products" => "products#index"

  #create actions routes
  get "/products/new" => "products#new"
  post "/products" => "products#create"

  #update actions routes
  get "/products/:id/edition" => "products#edit"
  patch "/products/:id" => "products#update"

  #delete actions routes
  delete "/products/:id" => "products#destroy"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attachment :photo

  belongs_to :user
  has_many :upvotes

  validates :user, presence: true
  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
  validates :category, inclusion: { in: %w(lifestyle fashion food art tech home),
    message: "%{value} is not a valid category" }

end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user, uniqueness: { scope: :product }
end

app/models/user.rb
class User < ApplicationRecord
  has_attachment :avatar

  has_many :products
  has_many :upvotes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def voted_for?(product)
    product.upvotes.where(user: self).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,        keys: [:avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    @today = Date.today.strftime("%d %b %Y")
  end

  def team
    @members = ["Bob", "Romain", "Seb"]
  end

  def join_us
    render plain: "send us a mail"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show, :edit, :update]
before_action :find_product, only: [:show, :edit, :update, :destroy]

def index

    if params[:category]
    @products = Product.where(category: params[:category])
    else
     @products = Product.all.order(created_at: :desc)
  end

def upvotes_rank
  @products = Product.select("products.*, COUNT(upvotes.id) AS upvotes_count").joins("LEFT JOIN upvotes ON products.id = upvotes.product_id").group("products.id").order("upvotes_count DESC")
end

def products_by_day
  day = Date.today
  @products = Product.select("products.*, COUNT(upvotes.id) AS upvotes_count").joins(:upvotes).where('upvotes.created_at >= ?', day).where('upvotes.created_at < ?', day + 1.day).order("upvotes_count DESC").group("products.id")
end


end

def show
  index = params[:id]
end

def new
  @product = Product.new
end

def create
  @product = Product.new(product_params)
  @product.user = current_user
  if @product.save
  redirect_to products_path
    else
      render :new
    end
end

def edit
end

def update
  if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end

end

def destroy
  @product.destroy
  redirect_to products_path
end

private

def product_params
  params.require(:product).permit(:name, :url, :tagline, :category, :photo)
end

def find_product
  @product = Product.friendly.find(params[:id])
end



end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @product.upvotes.create! user: current_user

    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end
  end

    def destroy
    upvote = Upvote.find(params[:id])
    @product = upvote.product

    upvote.destroy

    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= metamagic %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
  <%= render 'shared/flashes' %>
  <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/about.html.erb
<% meta title: "About - RushDaddy", description: "RushDaddy surfaces the best creative and innovative products, every day." %>

<div class="banner" style="background: linear-gradient(135deg, rgba(252,252,104,1) 0%, rgba(252,252,104,1) 25%, rgba(230,86,67,1) 100%);">
  <h1>Hello rushers !</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h3>What is RushDaddy ?</h3>
        <p> RushDaddy surfaces the best new creative and innovative products in fields like lifestyle, tech, fashion, home, food and art.</p>
      <h3>How it works ?</h3>
        <p>Every day, new products are posted on the website and users can vote for the best one. </p>
      <h3>Any questions ?</h3>
        <p>You can contact us <a href="https://www.facebook.com/RushDaddy-1340834209279528/?ref=bookmarks">here </a></p>
    </div>
  </div>
</div>

app/views/pages/grid.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "bg.jpg" %>');">
  <div class="banner-content">
    <h1>Cool products, every day.</h1>
    <p>Find creative and innovative products</p>
  </div>
  </div>

  <h3 class="text-center"><%= @today = Date.today.strftime("%d %b %Y") %></h3>


<div class="container">
  <div class="row">

    <div class="col-xs-10 col-sm-4">

    <% @products.each do |product| %>

    <%= link_to product_path(product) do %>
    <img src="http://unsplash.it/360/225?random" alt="kudoz">
    <% end %>


     <div class="product">
      <div class='product-upvote'>
        <div class="product-arrow"></div>
        <div class='product-count'>95</div>
     </div>

    <div class='product-body'>
    <h3><%= link_to product.name, product_path(product) %></h3>
    <p><%= product.tagline %></p>
    </div>

   <% end >

  </div>

  </div>

app/views/pages/home.html.erb
<% meta title: "RushDaddy - Cool products, every day !", description: "RushDaddy surfaces the best creative and innovative products, every day." %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "bg.jpg" %>');">
  <div class="banner-content">
    <h1>Wagon Hunt</h1>
    <p>Find best tech products</p>
    <p>
    A lot of new products on <%= @today %>
  </p>
    <p><%= link_to "All Products", products_path, class: "btn btn-primary" %></p>
  </div>
</div>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
      <%= f.input :name, placeholder: "Kudoz", label: "Product name" %>
      <%= f.input :url, placeholder: "http://kudoz.com", label: "Product url"  %>
      <%= f.input :tagline, placeholder: "Tagline", label: "Tagline"  %>
      <%= f.input :category, collection: ["lifestyle", "fashion", "food", "art", "tech", "home"], prompt: "Category"  %>
      <%= f.input :photo, as: :attachinary %>
      <%= f.button :submit, "Save", class:"btn btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-danger"  %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

    <h1 class="text-center">Edit product</h1>

    <%= render "form" %>


    </div>

  </div>

</div>

app/views/products/index.html.erb
<% meta title: "RushDaddy - Cool products, every day !", description: "RushDaddy surfaces the best creative and innovative products, every day." %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "bg.jpg" %>');">
  <div class="banner-content">
    <h1>Cool products, every day.</h1>
    <p>Find creative and innovative products</p>
  </div>
  </div>

<div class="container">
  <h3 class="products-by-date">

  <%= @today = Date.today.strftime("%d %b %Y") %></h3>

    <% @products.each_slice(3) do |products| %>
          <div class="row">
            <% products.each do |product| %>
                <div class="col-lg-4">

              <%= link_to product.url, target: "_blank" do %>

                <% if product.photo? %>
                  <%= cl_image_tag(product.photo.path, height: 250, width: 370, crop: :fill) %>
                <% else %>
                <img src="http://unsplash.it/370/250?random" alt="kudoz">
                <% end %>
              <% end %>

               <div class="product">

               <div class="upvote-container" id="product-<%= product.id %>">
                 <%= render 'upvotes/show', product: product %>
               </div>


          <div class='product-body'>
          <h3><%= link_to product.name, product.url, target: "_blank" %></h3>
          <p><%= product.tagline %></p>
          </div>

          <!--<ul class="list-inline product-controls hidden-sm hidden-xs">
            <li>
              <%= link_to product_path(product) do %>
              <i class="fa fa-eye"></i>
              <% end %>
          </li>

          <li><a href=""><i class="fa fa-share"></i></a></li>
          <li><a href=""><i class="fa fa-star"></i></a></li>
          </ul>-->

        </div>
      </div>
    <% end %>
  </div>
<div style="padding: 20px"></div>
<% end %>

</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

    <h1 class="text-center">Add product</h1>

    <%= render "form" %>


    </div>

  </div>

</div>

app/views/products/show.html.erb
<% meta title: "#{@product.name} - RushDaddy", description: "#{@product.tagline}" %>


<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @product.photo? ? cloudinary_url(@product.photo.path) : image_path("bg.jpg") %>');">
  <div class="banner-content">
    <h1><%= @product.name %></h1>
    <p><%= @product.tagline %>
    <span class="label label-default">
      <%= @product.category %>
    </span>
    </p>
    <p><%= link_to "Get it", @product.url, class: "btn btn-primary" %></p>


    <!--<% if @product.user %>
      <p>
        posted by <%= @product.user.email %>
      </p>
    <% end %>-->
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
  <%= image_tag"rushdaddy-logo.png" %>
  </a>
  <!-- Left Navigation -->
  <div class="navbar-wagon-left hidden-xs hidden-sm">
  <%= link_to "Lifestyle", products_path(category: "lifestyle"), class:"navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Tech", products_path(category: "tech"), class:"navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Fashion", products_path(category: "fashion"), class:"navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Home", products_path(category: "home"), class:"navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Food", products_path(category: "food"), class:"navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Art", products_path(category: "art"), class:"navbar-wagon-item navbar-wagon-link" %>


  </div>


  <% if user_signed_in? %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

   <a href="/about" class="navbar-wagon-item navbar-wagon-link">About</a>

    <!-- Search form -->
    <!--<form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>-->

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.avatar? %>
          <%= cl_image_tag current_user.avatar.path, width: 60, height: 60, crop: :fill, class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', :'data-toggle' => 'dropdown' %>
        <% else %>
          <img src="http://placehold.it/30x30" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% end %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to "+ Post product", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>

  <% else %>
    <div class="hidden-xs hidden-sm">
    <a href="/about" class="navbar-wagon-item navbar-wagon-link">About</a>
    <%= link_to "Login", new_user_session_path, class:"navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "+ Post product", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>

  <% end %>



  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/about" class="navbar-wagon-item navbar-wagon-link">About</a></li>
        <li><%= link_to "Login", new_user_session_path, class:"navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "+ Post product", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/upvotes/_show.html.erb
<% if user_signed_in? %>
  <% if current_user.voted_for?(product) %>
    <%= link_to upvote_path(current_user.upvotes.where(product: product).first), remote: true, method: :delete, class: 'product-upvote product-upvoted' do %>
      <div class="product-arrow"></div>
      <div class='product-count'>
        <%= product.upvotes.size %>
      </div>
    <% end %>
  <% else %>
    <%= link_to upvotes_path(product_id: product.id), remote: true, method: :post, class: 'product-upvote' do %>
      <div class="product-arrow"></div>
      <div class='product-count'>
        <%= product.upvotes.size %>
      </div>
    <% end %>
  <% end %>

<% else %>
<%= link_to new_product_path do %>
  <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class='product-count'>
      <%= product.upvotes.size %>
    </div>
  </div>
<% end %>
<% end %>

app/views/upvotes/create.js.erb
$('#product-<%= @product.id %>').html('<%= j render 'upvotes/show', product: @product %>');

app/views/upvotes/destroy.js.erb
$('#product-<%= @product.id %>').html('<%= j render 'upvotes/show', product: @product %>');